import Vue from 'vue'
import {
  Tabbar,
  TabbarItem,
  Icon,
  Col,
  Row,
  Form,
  Field,
  Button,
  NavBar,
  Image,
  Cell,
  CellGroup,
  GoodsActionIcon,
  PullRefresh,
  Card,
  Uploader,
  AddressList,
  AddressEdit,
  Sticky,
  Swipe,
  SwipeItem,
  Grid,
  TreeSelect,
  GridItem,
  Tag,
  Tabs,
  Tab,
  Search,
  Popup,
  GoodsActionButton,
  GoodsAction,
  NoticeBar,
  Stepper,
  ActionSheet,
  SubmitBar,
  PasswordInput,
  NumberKeyboard,
  Notify,
  Collapse,
  CollapseItem,
  Divider,
  Empty,
  List
} from 'vant'
Vue.use(List)
Vue.use(Empty)
Vue.use(Divider)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(NumberKeyboard)
Vue.use(PasswordInput)
Vue.use(SubmitBar)
Vue.use(ActionSheet)
Vue.use(NoticeBar)
Vue.use(Stepper)
Vue.use(Popup)
Vue.use(TreeSelect)
Vue.use(GoodsActionButton)
Vue.use(GoodsAction)
Vue.use(Search)
Vue.use(Tag)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Tabbar)
Vue.use(AddressList)
Vue.use(AddressEdit)
Vue.use(Card)
Vue.use(TabbarItem)
Vue.use(Icon)
Vue.use(Sticky)
Vue.use(Col)
Vue.use(Row)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(PullRefresh)
Vue.use(Form)
Vue.use(Field)
Vue.use(Image)
Vue.use(Button)
Vue.use(NavBar)
Vue.use(GoodsActionIcon)
Vue.use(Notify)
Vue.use(Uploader)
